name: Deploy Complex
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - run: docker build -t sag60068/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true sag60068/react-test npm test -- --coverage
      - run: docker build -t sag60068/multi-client ./client
      - run: docker build -t sag60068/multi-nginx ./nginx
      - run: docker build -t sag60068/multi-server ./server
      - run: docker build -t sag60068/multi-worker ./worker
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sag60068/multi-client
      - run: docker push sag60068/multi-nginx
      - run: docker push sag60068/multi-server
      - run: docker push sag60068/multi-worker

 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Dockergh-env
          existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip